Parameters:
  customstackid:
    Description: stack id of a user
    Type: String
    Default: "101"
  environment:
    Description: working environment
    Type: String
    Default: "local"


Resources:
  S3SourceBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName:
        !Sub flask-sourcebucketflask-${customstackid}-${environment}